#!/data/data/com.termux/files/usr/bin/bash
set -Eeuo pipefail

OWNER="Atlas-Ascend"
REPO="WOOK"
GA="$HOME/.ghost-atlas"
PRIMARY="$GA/games/WOOK"
SAFE="$GA/campaigns/WOOK-ENCYCLOPEDIA-COMMAND-TO-PROOF-001/repo"
PUB="$GA/campaigns/WOOK-C00-MAIN-PUBLISH/repo"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"

# Prefer an explicitly selected production checkout, then the encyclopedia safe
# checkout, then the primary checkout. This publisher NEVER rebuilds WOOK.
if [ -n "${WOOK_ROOT:-}" ] && [ -d "$WOOK_ROOT/.git" ]; then
  SRC="$WOOK_ROOT"
elif [ -d "$SAFE/.git" ]; then
  SRC="$SAFE"
elif [ -d "$PRIMARY/.git" ]; then
  SRC="$PRIMARY"
else
  echo "WOOK_SOURCE_CHECKOUT=MISSING"
  exit 10
fi

cd "$SRC"

echo "======================================================================"
echo " WOOK C00 // PROMOTE GENERATED MVP TO MAIN"
echo "======================================================================"
echo "SOURCE_ROOT=$SRC"
echo "SOURCE_HEAD=$(git rev-parse HEAD)"

command -v git >/dev/null || { echo "GIT=MISSING"; exit 11; }
command -v jq >/dev/null || { echo "JQ=MISSING"; exit 12; }
command -v curl >/dev/null || { echo "CURL=MISSING"; exit 13; }
command -v sha256sum >/dev/null || { echo "SHA256SUM=MISSING"; exit 14; }

STATE="$SRC/docs/proof/c0-golden-slice/state.json"
[ -s "$STATE" ] || { echo "C00_STATE=MISSING"; exit 20; }

# Hosting an MVP candidate does not require human VISUAL_QA yet, but it does
# require every automated gameplay/build gate through ROM to have passed.
pre=(
  PAPA_WOOK_CONTROLLER SNIFFANY HANDSTAND_DAN RACCOON_ENCOUNTER
  CROCS_0_TO_2 COLLISION_TOPOLOGY HUD PHONE INVENTORY QUEST_LOG
  GROUNDSCORE RESPONSIBILITY WOOK_KARMA SIDE_QUEST SECRET SAVE_RELOAD
  GA_EXIT NATIVE_WEB ROM
)
for gate in "${pre[@]}"; do
  v="$(jq -r --arg g "$gate" '.gates[$g] // "MISSING"' "$STATE")"
  [ "$v" = "PASS" ] || {
    echo "PUBLISH_PRECONDITION_${gate}=$v"
    echo "PUBLICATION=BLOCKED_AT_FIRST_UNPROVEN_GATE"
    exit 21
  }
  echo "PASS=$gate"
done

# Prefer the dedicated C00 MVP export if the prior MVP command produced it.
# Otherwise use the latest integrated native output generated by the C00 packet
# train. This is a promotion operation only; no compilation occurs here.
if [ -s "$SRC/site/c00-mvp/index.html" ]; then
  SOURCE_WEB="$SRC/site/c00-mvp"
  echo "SOURCE_WEB_CLASS=C00_MVP_EXPORT"
elif [ -s "$SRC/site/gbstudio/index.html" ]; then
  SOURCE_WEB="$SRC/site/gbstudio"
  echo "SOURCE_WEB_CLASS=LATEST_INTEGRATED_NATIVE_EXPORT"
else
  echo "SOURCE_NATIVE_WEB=MISSING"
  exit 22
fi

if [ -s "$SRC/releases/mvp/c00/rom/WOOK-C00-MVP.gb" ]; then
  SOURCE_ROM="$SRC/releases/mvp/c00/rom/WOOK-C00-MVP.gb"
  echo "SOURCE_ROM_CLASS=C00_MVP_ROM"
elif [ -s "$SRC/releases/native/rom/WOOK.gb" ]; then
  SOURCE_ROM="$SRC/releases/native/rom/WOOK.gb"
  echo "SOURCE_ROM_CLASS=LATEST_INTEGRATED_NATIVE_ROM"
else
  echo "SOURCE_ROM=MISSING"
  exit 23
fi

ROM_SHA="$(sha256sum "$SOURCE_ROM" | awk '{print $1}')"
WEB_SHA="$(sha256sum "$SOURCE_WEB/index.html" | awk '{print $1}')"
STATE_SHA="$(sha256sum "$STATE" | awk '{print $1}')"
SOURCE_HEAD="$(git rev-parse HEAD)"

echo "ROM_SHA256=$ROM_SHA"
echo "WEB_SHA256=$WEB_SHA"
echo "STATE_SHA256=$STATE_SHA"

mkdir -p "$(dirname "$PUB")"
if [ ! -d "$PUB/.git" ]; then
  git clone "https://github.com/$OWNER/$REPO.git" "$PUB"
fi

cd "$PUB"
git fetch origin main
git reset --hard origin/main
git clean -fd

rm -rf site/gbstudio site/c00-mvp releases/mvp/c00
mkdir -p site/gbstudio site/c00-mvp releases/mvp/c00/rom docs/proof/releases
cp -a "$SOURCE_WEB/." site/gbstudio/
cp -a "$SOURCE_WEB/." site/c00-mvp/
cp "$SOURCE_ROM" releases/mvp/c00/rom/WOOK-C00-MVP.gb

# Keep /site/golden/ as the permanent public URL. main already routes that
# stable URL into site/gbstudio, which is replaced above with the current C00
# generated native export.
test -s site/golden/index.html || { echo "STABLE_GOLDEN_ROUTER=MISSING"; exit 30; }
test -s site/gbstudio/index.html || { echo "PROMOTED_GBSTUDIO=MISSING"; exit 31; }
test -s site/c00-mvp/index.html || { echo "PROMOTED_C00_MVP=MISSING"; exit 32; }
test -s releases/mvp/c00/rom/WOOK-C00-MVP.gb || { echo "PROMOTED_ROM=MISSING"; exit 33; }

git add site/gbstudio site/c00-mvp releases/mvp/c00/rom/WOOK-C00-MVP.gb
if git diff --cached --quiet; then
  echo "PUBLICATION_CONTENT=ALREADY_CURRENT"
else
  git commit -m "release: promote generated WOOK C00 MVP to main $STAMP"
  git push origin main
fi

BUILD_COMMIT="$(git rev-parse HEAD)"
REMOTE="$(git ls-remote origin refs/heads/main | awk '{print $1}')"
[ "$BUILD_COMMIT" = "$REMOTE" ] || {
  echo "MAIN_SHA_EQUALITY=FAIL"
  echo "LOCAL=$BUILD_COMMIT"
  echo "REMOTE=$REMOTE"
  exit 40
}
echo "MAIN_SHA_EQUALITY=PASS"

STABLE_URL="https://raw.githack.com/$OWNER/$REPO/main/site/golden/index.html"
DIRECT_URL="https://raw.githack.com/$OWNER/$REPO/main/site/c00-mvp/index.html"
ROM_URL="https://raw.githubusercontent.com/$OWNER/$REPO/main/releases/mvp/c00/rom/WOOK-C00-MVP.gb"

for pair in "STABLE:$STABLE_URL" "DIRECT:$DIRECT_URL" "ROM:$ROM_URL"; do
  name="${pair%%:*}"; url="${pair#*:}"
  code="000"
  for _ in 1 2 3 4 5 6; do
    code="$(curl -L -sS -o /dev/null -w '%{http_code}' "$url" || true)"
    [ "$code" = 200 ] && break
    sleep 3
  done
  echo "${name}_HTTP=$code"
  [ "$code" = 200 ] || exit 41
done

RECEIPT="docs/proof/releases/WOOK-C00-MAIN-PUBLICATION-$STAMP.json"
jq -n \
  --arg ts "$STAMP" \
  --arg source "$SOURCE_HEAD" \
  --arg build "$BUILD_COMMIT" \
  --arg rom "$ROM_SHA" \
  --arg web "$WEB_SHA" \
  --arg state "$STATE_SHA" \
  --arg stable "$STABLE_URL" \
  --arg direct "$DIRECT_URL" \
  --arg romurl "$ROM_URL" \
  '{
    schema:"ghost-atlas.wook.c00.main-publication.v1",
    timestamp:$ts,
    source_worktree_head:$source,
    publication_build_commit:$build,
    proof:{automated_c00_through_rom:"PASS",main_sha_equality:"PASS",stable_http:"200",direct_http:"200",rom_http:"200"},
    hashes:{rom:$rom,native_web:$web,c00_state:$state},
    urls:{stable:$stable,direct_c00:$direct,rom:$romurl},
    truth:{visual_qa:"PENDING_OR_SEPARATELY_RECORDED",final_c00_release:"NOT_IMPLIED"},
    result:"WOOK_C00_MAIN_HOSTING_PASS"
  }' > "$RECEIPT"
cp "$RECEIPT" docs/proof/releases/C00-MAIN-PUBLICATION-LATEST.json

git add "$RECEIPT" docs/proof/releases/C00-MAIN-PUBLICATION-LATEST.json
git commit -m "proof: WOOK C00 main hosting $STAMP"
git push origin main
FINAL_HEAD="$(git rev-parse HEAD)"
FINAL_REMOTE="$(git ls-remote origin refs/heads/main | awk '{print $1}')"
[ "$FINAL_HEAD" = "$FINAL_REMOTE" ] || { echo "FINAL_MAIN_SHA_EQUALITY=FAIL"; exit 42; }

echo "======================================================================"
echo " WOOK C00 MAIN HOSTING = PASS"
echo "======================================================================"
echo "STABLE_PLAY_URL=$STABLE_URL"
echo "DIRECT_C00_URL=$DIRECT_URL"
echo "ROM_URL=$ROM_URL"
echo "ROM_SHA256=$ROM_SHA"
echo "PUBLICATION_BUILD_COMMIT=$BUILD_COMMIT"
echo "FINAL_PROOF_COMMIT=$FINAL_HEAD"
echo "WOOK_C00_MAIN_HOSTING_PASS"
echo "======================================================================"
